apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: DS_PROM_VALENCE
        type: prometheus
        access: proxy
        url: http://prometheus-valence.valence-system:9090
        editable: false
        version: 1

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-providers
data:
  default.yaml: |
    apiVersion: 1
    providers:
      - name: 'default'
        org_id: 1
        folder: ''
        type: 'file'
        options:
          path: '/var/lib/grafana/dashboards'
