apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: todo-backend-django-valence
  labels:
    app: todo-backend-django-valence
    slo: slo-webapps
  annotations:
    valence.io/optimizer.configure: "true"
spec:
  revisionHistoryLimit: 3
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 10%
  template:
    spec:
      restartPolicy: Always
      containers:
        - name: envoy
          image: valencenet/envoyproxy:0.3.0
          imagePullPolicy: IfNotPresent
          env:
          - name: SERVICE_PORT_VALUE
            value: "8000"
          ports:
            - containerPort: 8081
              name: envoy-sidecar
            - containerPort: 8181
              name: envoy-metrics
        - image: manifoldco/todo-backend-django:latest
          imagePullPolicy: IfNotPresent
          name: todo-backend-django-valence
          resources:
            limits:
              cpu: 500m
              memory: 500M
            requests:
              cpu: 250m
              memory: 250M
          env:
            - name: PORT
              value: "8000"
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /todos
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 30
            failureThreshold: 30
