apiVersion: v1
kind: Service
metadata:
  name: todo-backend-django-valence
  labels:
    valence.net/prometheus: "true"
spec:
  type: NodePort
  ports:
  - name: headless
    port: 80
    targetPort: 8081
  - name: prometheus
    port: 8181
    targetPort: 8181
  selector:
    app: todo-backend-django-valence